# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12user_service.proto\x12\x0buserservice\"!\n\x0eGetUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"#\n\x0fGetUsersRequest\x12\x10\n\x08user_ids\x18\x01 \x03(\x05\"g\n\x0cUserResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05\x66name\x18\x02 \x01(\t\x12\x0c\n\x04\x63ity\x18\x03 \x01(\t\x12\r\n\x05phone\x18\x04 \x01(\x03\x12\x0e\n\x06height\x18\x05 \x01(\x02\x12\x0f\n\x07married\x18\x06 \x01(\x08\x32\xa0\x01\n\x0bUserService\x12\x45\n\x0bGetUserByID\x12\x1b.userservice.GetUserRequest\x1a\x19.userservice.UserResponse\x12J\n\rGetUsersByIDs\x12\x1c.userservice.GetUsersRequest\x1a\x19.userservice.UserResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETUSERREQUEST']._serialized_start=35
  _globals['_GETUSERREQUEST']._serialized_end=68
  _globals['_GETUSERSREQUEST']._serialized_start=70
  _globals['_GETUSERSREQUEST']._serialized_end=105
  _globals['_USERRESPONSE']._serialized_start=107
  _globals['_USERRESPONSE']._serialized_end=210
  _globals['_USERSERVICE']._serialized_start=213
  _globals['_USERSERVICE']._serialized_end=373
# @@protoc_insertion_point(module_scope)
